version: '3.7'

services:
  confluence:
    image: atlassian/confluence-server
    container_name: confluence
    hostname: confluence
    restart: unless-stopped
    networks:
      - confluencenet
    volumes:
      - /var/lib/docker/volumes/confluencedata:/var/atlassian/application-data/confluence:rw,z
      - /var/lib/docker/volumes/ca/cacerts:/opt/java/openjdk/jre/lib/security/cacerts
   # ports:
   #   - '8090:8090'
   #   - '8091:8091'
    environment:
      - 'TZ=Europe/Moscow'
      - 'JVM_MINIMUM_MEMORY=4g'
      - 'JVM_MAXIMUM_MEMORY=8g'
      - 'ATL_PROXY_NAME=wiki.example.com'
      - 'ATL_PROXY_PORT=443'
      - 'ATL_TOMCAT_SCHEME=https'
      - 'ATL_TOMCAT_SECURE=true'
      - 'ATL_TOMCAT_MAXTHREADS=400'
      - 'ATL_TOMCAT_MINSPARETHREADS=25'
      - 'ATL_TOMCAT_ACCEPTCOUNT=100'
      #- 'JVM_SUPPORT_RECOMMENDED_ARGS=-Djavax.net.ssl.trustStore="/var/atlassian/application-data/confluence/cacerts" -Djavax.net.ssl.trustStorePassword="somepassword"'

      #- 'ATL_TOMCAT_CONTEXTPATH=/confluence'
    command: apt-get install -y graphviz

  postgresql:
    image: postgres:9.6-alpine
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    networks:
      - confluencenet
    volumes:
      - /var/lib/docker/volumes/postgresqldata:/var/lib/postgresql/data:rw,z
    environment:
      - 'TZ=Europe/Moscow'
      - 'POSTGRES_USER=confluencedb'
      - 'POSTGRES_PASSWORD=somepassworddb'
      - 'POSTGRES_DB=confluencedb'
      - 'POSTGRES_ENCODING=UTF8'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    #ports:
    #  - '5432:5432'

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    networks:
      - confluencenet
    ports:
     - '8080:8080'

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - /var/lib/docker/volumes/nginx:/etc/nginx:rw,z
    ports:
    #- '80:80'
     - '443:443'
    environment:
      - 'TZ=Europe/Moscow'
    networks:
      - confluencenet
networks:
  confluencenet:
    driver: bridge